using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Continentes : MonoBehaviour
{

    public static int nivelSeleccionado=0;

    public void setNivel(int nivel){
        nivelSeleccionado=nivel;
    }
    public static string[] Asia = {
        "Afganistán",
        "Armenia",
        "Azerbaiyán",
        "Bahréin",
        "Bangladés",
        "Bután",
        "Brunéi",
        "Camboya",
        "China",
        "Chipre",
        "Timor Oriental",
        "Georgia",
        "Hong Kong",
        "India",
        "Indonesia",
        "Irán",
        "Irak",
        "Israel",
        "Japón",
        "Jordán",
        "Kazajstán",
        "Kuwait",
        "Kirguistán",
        "Laos",
        "Líbano",
        "Macao",
        "Malasia",
        "Maldivas",
        "Mongolia",
        "Birmania",
        "Nepal",
        "Corea del Norte",
        "Omán",
        "Pakistán",
        "Palestina",
        "Filipinas",
        "Katar",
        "Arabia Saudita",
        "Singapur",
        "Corea del Sur",
        "Sri Lanka",
        "Siria",
        "Tayikistán",
        "Tailandia",
        "Turquía",
        "Turkmenistán",
        "Emiratos Árabes Unidos",
        "Uzbekistán",
        "Vietnam",
        "Yemen"
    };
    public static string[] America = {
        "Anguila",
        "Antigua y Barbuda",
        "Argentina",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belice",
        "Islas Bermudas",
        "Bolivia",
        "Brasil",
        "Territorio Británico del Océano Índico",
        "Brunéi",
        "Canadá",
        "Cabo Verde",
        "Islas Caimán",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "República Dominicana",
        "Ecuador",
        "El Salvador",
        "Islas Malvinas",
        "Guayana Francesa",
        "Groenlandia",
        "Granada",
        "Guadalupe",
        "Guatemala",
        "Haití",
        "Honduras",
        "Jamaica",
        "Martinica",
        "México",
        "Montserrat",
        "Antillas Holandesas",
        "Nicaragua",
        "Panamá",
        "Paraguay",
        "Perú",
        "Puerto Rico",
        "Santa Lucía",
        "San Pedro y Miquelón",
        "San Vicente y las Granadinas",
        "Surinam",
        "Trinidad y Tobago",
        "Islas Turcas y Caicos",
        "Estados Unidos",
        "Uruguay",
        "Venezuela",
        "Islas Vírgenes Británicas",
        "Islas Vírgenes, EE. UU.",
    };
    public static string[] Europa ={
        "Albania",
        "Andorra",
        "Austria",
        "Bielorrusia",
        "Bélgica",
        "Bosnia y Herzegovina",
        "Bulgaria",
        "Croacia",
        "Republica checa",
        "Dinamarca",
        "Inglaterra",
        "Estonia",
        "Islas Faroe",
        "Finlandia",
        "Francia",
        "Alemania",
        "Gibraltar",
        "Grecia",
        "Santa Sede (Ciudad del Vaticano)",
        "Hungría",
        "Islandia",
        "Irlanda",
        "Italia",
        "Letonia",
        "Liechtenstein",
        "Lituania",
        "Luxemburgo",
        "Macedonia del Norte",
        "Malta",
        "Moldavia",
        "Mónaco",
        "Montenegro",
        "Países Bajos",
        "Irlanda del Norte",
        "Noruega",
        "Polonia",
        "Portugal",
        "Rumania",
        "Federación Rusa",
        "San Marino",
        "Escocia",
        "Serbia",
        "Eslovaquia",
        "Eslovenia",
        "España",
        "Svalbard y Jan Mayen",
        "Suecia",
        "Suiza",
        "Ucrania",
        "Reino Unido",
        "Gales",
    };
    public static string[] Africa ={
        "Argelia",
        "Angola",
        "Benín",
        "Botsuana",
        "Territorio Británico del Océano Índico",
        "Burkina Faso",
        "Burundi",
        "Camerún",
        "Cabo Verde",
        "República Centroafricana",
        "Chad",
        "Comoras",
        "Congo",
        "Yibuti",
        "Egipto",
        "Guinea Ecuatorial",
        "Eritrea",
        "Etiopía",
        "Gabón",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bisáu",
        "Costa de Marfil",
        "Kenia",
        "Lesoto",
        "Liberia",
        "Jamahiriya Árabe Libia",
        "Madagascar",
        "Malaui",
        "Malí",
        "Mauritania",
        "Mauricio",
        "Mayotte",
        "Marruecos",
        "Mozambique",
        "Namibia",
        "Níger",
        "Nigeria",
        "Reunión",
        "Ruanda",
        "Santa Elena",
        "Santo Tomé y Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leona",
        "Somalia",
        "Sudáfrica",
        "Sudán del Sur",
        "Sudán",
        "Suazilandia",
        "Tanzania",
        "La República Democrática del Congo",
        "Ir",
        "Túnez",
        "Uganda",
        "Sahara Occidental",
        "Zambia",
        "Zimbabue"
    };
    public static string[] Oceania = {
        "Samoa Americana",
        "Australia",
        "Isla de Navidad",
        "Islas Cocos (Keeling)",
        "Islas Cook",
        "Islas Fiyi",
        "Polinesia francés",
        "Guam",
        "Kiribati",
        "Islas Marshall",
        "Micronesia, Estados Federados de",
        "Nauru",
        "Nueva Caledonia",
        "Nueva Zelanda",
        "Niue",
        "Isla Norfolk",
        "Islas Marianas del Norte",
        "Palaus",
        "Papúa Nueva Guinea",
        "Pitcairn",
        "Samoa",
        "Islas Salomón",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "Islas menores alejadas de los Estados Unidos",
        "Vanuatu",
        "Wallis y Futuna"
    };
    
    public static string[] mundo = {};
}