using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Continentes : MonoBehaviour
{

    public static int nivelSeleccionado=0;

    public void setNivel(int nivel){
        nivelSeleccionado=nivel;
    }
    public static string[] Asia = {
        "Afganistán",
		"Arabia Saudita",
        "Armenia",
        "Azerbaiyán",
        "Baréin",
        "Bangladesh",
        "Brunéi",
        "Bután",
        "Camboya",
        "Catar",
        "China",
		"Corea del Norte",
        "Corea del Sur",
		"Egipto",
		"Emiratos Árabes Unidos",
		"Filipinas",
		"Georgia",
        "Hong Kong",
		"India",
        "Indonesia",
        "Irak",
        "Irán",
        "Israel",
        "Japón",
        "Jordania",
        "Kazajistán",
        "Kirguistán",
		"Kuwait",
        "Laos",
        "Líbano",
        "Macao",
        "Malasia",
        "Maldivas",	
		"Mongolia",
		"Myanmar",
        "Nepal",
        "Omán",
        "Pakistán",
        "Palestina",
		"Rusia",
        "Singapur",
        "Siria",
        "Sri Lanka",
        "Tailandia",
		"Tayikistán",
        "Timor Oriental",
        "Turkmenistán",
        "Turquía",
        "Uzbekistán",
        "Vietnam",
        "Yemen"
    };
    public static string[] America = {
  "Anguila",
        "Antigua y Barbuda",
		"Aruba",
		"Bahamas",
        "Barbados",
        "Belice",
        "Bermudas",
		"Canadá",
		"Caribe Neerlandés",
		"Costa Rica",
        "Cuba",
		"Curazao",
		"Dominica",
        "El Salvador",
		"Estados Unidos",
		"Granada",
        "Groenlandia",
		"Guadalupe",
        "Guatemala",
		"Haití",
        "Honduras",
		"Islas Caimán", 
		"Islas Turcas y Caicos",
		"Islas Vírgenes de los Estados Unidos",
		"Islas Vírgenes Británicas",
		"Jamaica",
        "Martinica",
        "México",
        "Montserrat",
        "Nicaragua",
        "Panamá",
		"Puerto Rico",
		"República Dominicana",
		"San Martín (Francia)",
		"San Bartolomé",
		"San Cristóbal y Nieves",
		"San Pedro y Miquelón",
		"San Vicente y las Granadinas",
		"Santa Lucía",
		"San Martín (Países Bajos)",
        "Argentina",
        "Bolivia",
        "Brasil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guayana Francesa",
		"Islas Malvinas",
        "Paraguay",
        "Perú",
        "Surinam",
        "Trinidad y Tobago",
        "Uruguay",
        "Venezuela",
    };
    public static string[] Europa ={
		"Åland",
        "Albania",
		"Alemania",
        "Andorra",
        "Austria",
		"Bélgica",
        "Bielorrusia",
        "Bosnia y Herzegovina",
        "Bulgaria",
        "República Checa",
		"Chipre",
		"Ciudad del Vaticano",
		"Croacia",
        "Dinamarca",
		"Eslovenia",
        "España",
		"Estonia",
		"Finlandia",
        "Francia",
        "Gibraltar",
		"Grecia",
		"Guernsey",
		"Hungría",
		"Irlanda",
		"Isla de Man",
        "Islandia",
        "Islas Feroe",
		"Svalbard y Jan Mayen",
        "Italia",
		"Jersey",
		"Kosovo",
        "Letonia",
        "Liechtenstein",
        "Lituania",
        "Luxemburgo",
        "Macedonia del Norte",
        "Malta",
        "Moldavia",
        "Mónaco",
        "Montenegro",
		"Noruega",
		"Países Bajos",
        "Polonia",
        "Portugal",
		"Reino Unido",
		"Eslovaquia",
        "Rumania",
        "Rusia",
        "San Marino",
		"Serbia",
		"Suecia",
		"Suiza",
		"Turquía", 
        "Ucrania",
    };
    public static string[] Africa ={
        "Angola",
        "Argelia",
        "Benín",
        "Botsuana",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Camerún",
		"Chad",
        "Comoras",
        "Congo",
		"Congo (Rep. Dem.)",
		"Costa de Marfil",
		"Yibuti",
		"Egipto",
        "Eritrea",
        "Etiopía",
        "Gabón",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea Ecuatorial",
        "Guinea-Bisáu",
        "Kenia",
        "Lesoto",
        "Liberia",
		"Libia",
		"Madagascar",
        "Malawi",
        "Malí",
		"Marruecos",
		"Mauricio",
        "Mauritania",
        "Mayotte",
        "Mozambique",
        "Namibia",
        "Níger",
        "Nigeria",
		"República Centroafricana",
		"Sudáfrica",
        "Reunión",
        "Ruanda",
		"Sahara Occidental",
        "Santo Tomé y Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leona",
        "Somalia",
        "Suazilandia",
        "Sudán",
        "Sudán del Sur",
        "Tanzania",
		"Territorio Británico del Océano Índico",
        "Togo",
        "Túnez",
        "Uganda",
        "Zambia",
        "Zimbabue"
    };
    public static string[] Oceania = {
     "Australia",
	 "Fiyi",
	 "Guam",
	 "Indonesia",
     "Isla de Navidad",
	 "Isla Norfolk",
     "Islas Cocos",
     "Islas Cook",
	 "Islas Marianas del Norte",
	 "Islas Marshall",
	 "Islas Pitcairn",
	 "Islas Salomón",
	 "Tokelau",
     "Kiribati",
	 "Micronesia",
     "Nauru",
	 "Niue",
     "Nueva Caledonia",
     "Nueva Zelanda",
     "Palaos",
     "Papúa Nueva Guinea",
     "Polinesia Francesa",
     "Samoa",
     "Samoa Americana",
     "Tonga",
     "Tuvalu",
     "Vanuatu",
     "Wallis y Futuna",
    };
    
    public static string[] Mundo = {
        "Afganistán",
		"Arabia Saudita",
        "Armenia",
        "Azerbaiyán",
        "Baréin",
        "Bangladesh",
        "Brunéi",
        "Bután",
        "Camboya",
        "Catar",
        "China",
		"Corea del Norte",
        "Corea del Sur",
		"Egipto",
		"Emiratos Árabes Unidos",
		"Filipinas",
		"Georgia",
        "Hong Kong",
		"India",
        "Indonesia",
        "Irak",
        "Irán",
        "Israel",
        "Japón",
        "Jordania",
        "Kazajistán",
        "Kirguistán",
		"Kuwait",
        "Laos",
        "Líbano",
        "Macao",
        "Malasia",
        "Maldivas",	
		"Mongolia",
		"Myanmar",
        "Nepal",
        "Omán",
        "Pakistán",
        "Palestina",
		"Rusia",
        "Singapur",
        "Siria",
        "Sri Lanka",
        "Tailandia",
		"Tayikistán",
        "Timor Oriental",
        "Turkmenistán",
        "Turquía",
        "Uzbekistán",
        "Vietnam",
        "Yemen",
        "Angola",
        "Argelia",
        "Benín",
        "Botsuana",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Camerún",
		"Chad",
        "Comoras",
        "Congo",
		"Congo (Rep. Dem.)",
		"Costa de Marfil",
		"Yibuti",
		"Egipto",
        "Eritrea",
        "Etiopía",
        "Gabón",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea Ecuatorial",
        "Guinea-Bisáu",
        "Kenia",
        "Lesoto",
        "Liberia",
		"Libia",
		"Madagascar",
        "Malawi",
        "Malí",
		"Marruecos",
		"Mauricio",
        "Mauritania",
        "Mayotte",
        "Mozambique",
        "Namibia",
        "Níger",
        "Nigeria",
		"República Centroafricana",
		"Sudáfrica",
        "Reunión",
        "Ruanda",
		"Sahara Occidental",
        "Santo Tomé y Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leona",
        "Somalia",
        "Suazilandia",
        "Sudán",
        "Sudán del Sur",
        "Tanzania",
		"Territorio Británico del Océano Índico",
        "Togo",
        "Túnez",
        "Uganda",
        "Zambia",
        "Zimbabue",
		"Åland",
        "Albania",
		"Alemania",
        "Andorra",
        "Austria",
		"Bélgica",
        "Bielorrusia",
        "Bosnia y Herzegovina",
        "Bulgaria",
        "República Checa",
		"Chipre",
		"Ciudad del Vaticano",
		"Croacia",
        "Dinamarca",
		"Eslovenia",
        "España",
		"Estonia",
		"Finlandia",
        "Francia",
        "Gibraltar",
		"Grecia",
		"Guernsey",
		"Hungría",
		"Irlanda",
		"Isla de Man",
        "Islandia",
        "Islas Feroe",
		"Svalbard y Jan Mayen",
        "Italia",
		"Jersey",
		"Kosovo",
        "Letonia",
        "Liechtenstein",
        "Lituania",
        "Luxemburgo",
        "Macedonia del Norte",
        "Malta",
        "Moldavia",
        "Mónaco",
        "Montenegro",
		"Noruega",
		"Países Bajos",
        "Polonia",
        "Portugal",
		"Reino Unido",
		"Eslovaquia",
        "Rumania",
        "Rusia",
        "San Marino",
		"Serbia",
		"Suecia",
		"Suiza",
		"Turquía", 
        "Ucrania",
     "Australia",
	 "Fiyi",
	 "Guam",
	 "Indonesia",
     "Isla de Navidad",
	 "Isla Norfolk",
     "Islas Cocos",
     "Islas Cook",
	 "Islas Marianas del Norte",
	 "Islas Marshall",
	 "Islas Pitcairn",
	 "Islas Salomón",
	 "Tokelau",
     "Kiribati",
	 "Micronesia",
     "Nauru",
	 "Niue",
     "Nueva Caledonia",
     "Nueva Zelanda",
     "Palaos",
     "Papúa Nueva Guinea",
     "Polinesia Francesa",
     "Samoa",
     "Samoa Americana",
     "Tonga",
     "Tuvalu",
     "Vanuatu",
     "Wallis y Futuna",
        "Anguila",
        "Antigua y Barbuda",
		"Aruba",
		"Bahamas",
        "Barbados",
        "Belice",
        "Bermudas",
		"Canadá",
		"Caribe Neerlandés",
		"Costa Rica",
        "Cuba",
		"Curazao",
		"Dominica",
        "El Salvador",
		"Estados Unidos",
		"Granada",
        "Groenlandia",
		"Guadalupe",
        "Guatemala",
		"Haití",
        "Honduras",
		"Islas Caimán", 
		"Islas Turcas y Caicos",
		"Islas Vírgenes de los Estados Unidos",
		"Islas Vírgenes Británicas",
		"Jamaica",
        "Martinica",
        "México",
        "Montserrat",
        "Nicaragua",
        "Panamá",
		"Puerto Rico",
		"República Dominicana",
		"San Martín (Francia)",
		"San Bartolomé",
		"San Cristóbal y Nieves",
		"San Pedro y Miquelón",
		"San Vicente y las Granadinas",
		"Santa Lucía",
		"San Martín (Países Bajos)",
        "Argentina",
        "Bolivia",
        "Brasil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guayana Francesa",
		"Islas Malvinas",
        "Paraguay",
        "Perú",
        "Surinam",
        "Trinidad y Tobago",
        "Uruguay",
        "Venezuela",
    };
}